export const Feeling = [
  {
    id: "happy",
    title: "Happy",
    path: "/happy",
    color: ["#FED049", "#68B984", "#CFFDE1"],
    verse: "28:77",
  },
  {
    id: "sad",
    title: "Sad",
    path: "/sad",
    color: ["#76A5FF", "#878EBA", "#AABBFF"],
    verse: "3:25",
  },
  {
    id: "angry",
    title: "Angry",
    path: "/angry",
    color: ["#E4508F", "#FF8868", "#FFD35C"],
    verse: "3:159",
  },
  {
    id: "scared",
    title: "Scared",
    path: "/scared",
    color: ["#6B6B6B", "#D8BFD8", "#D8BFD8"],
    verse: "40:44",
  },
  {
    id: "weak",
    title: "Weak",
    path: "/weak",
    color: ["#93BFCF", "#85AAC7", "#C2F9FF"],
    verse: "4:28",
  },
  {
    id: "lonely",
    title: "Lonely",
    path: "/lonely",
    color: ["#6B6B6B", "#20B2AA", "#FFD1DC"],
    verse: "20:46",
  },
  {
    id: "worried",
    title: "Worried",
    path: "/worried",
    color: ["#B08BBB", "#8587C1", "#7B5986"],
    verse: "2:45",
  },
  {
    id: "anxious",
    title: "Anxious",
    path: "/anxious",
    color: ["#6B6B6B", "#B0C4DE", "#FFFACD"],
    verse: "8:30",
  },
  {
    id: "forgiveness",
    title: "Need Forgiveness",
    path: "/forgiveness",
    color: ["#1572A1", "#4372AD", "#AE64A6"],
    verse: "11:52",
  },
  {
    id: "need-courage",
    title: "Need Courage",
    path: "/need-courage",
    color: ["#F1935C", "#FF878C", "#FFBEC1"],
    verse: "55:60",
  },
  {
    id: "need-direction",
    title: "Need Direction",
    path: "/need-direction",
    color: ["#555555", "#202020", "#505050"],
    verse: "64:11",
  },
  {
    id: "peace",
    title: "Need Peace",
    path: "/need-peace",
    color: ["#B0C4DE", "#20B2AA", "#FFDAB9"],
    verse: "5:16",
  },
  {
    id: "sinned",
    title: "Sinned",
    path: "/sinned",
    color: ["#535962", "#505680", "#60728C"],
    verse: "39:53",
  },
  {
    id: "danger",
    title: "In Danger",
    path: "/danger",
    color: ["#EB6383", "#BD574E", "#D45079"],
    verse: "3:54",
  },
  {
    id: "faith",
    title: "Lack of Faith",
    path: "/faith",
    color: ["#6E85B7", "#32A5D4", "#00C3D5"],
    verse: "13:28",
  },
  {
    id: "sexually-discriminated",
    title: "Sexually Discriminated",
    path: "/sexually-discriminated",
    color: ["#BA90C6", "#B2A4FF", "#E8A0BF"],
    verse: "33:35",
  },
  {
    id: "racially-discriminated",
    title: "Racially Discriminated",
    path: "/racially-discriminated",
    color: ["#D3D3D3", "#20B2AA", "#FFD1DC"],
    verse: "49:13",
  },
  {
    id: "depressed",
    title: "Depressed",
    path: "/depressed",
    color: ["#374259", "#A4ABBD", "#404756"],
    verse: "3:139",
  },
  {
    id: "need-love",
    title: "Need Love and Tranquility",
    path: "/need-love",
    color: ["#FF8787", "#F8C4B4", "#BCE29E"],
    verse: "30:21",
  },
  {
    id: "not-appreciated",
    title: "Not Appreciated",
    path: "/not-appreciated",
    color: ["#A97155", "#8FBDD3", "#BE8C63"],
    verse: "76:22",
  },
  {
    id: "loser",
    title: "Like a Loser",
    path: "/loser",
    color: ["#D45D79", "#EA9085", "#F2D388"],
    verse: "12:87",
  },
  {
    id: "underpriviledged",
    title: "Underpriviledged",
    path: "/underpriviledged",
    color: ["#85603F", "#9E7540", "#766161"],
    verse: "14:34",
  },
  {
    id: "hardships",
    title: "Tired of Hardships",
    path: "/hardships",
    color: ["#838383", "#474554", "#707B83"],
    verse: "94:5",
  },
];
