export const Feeling = [
  {
    id: "happy",
    title: "Happy",
    path: "/happy",
    color: ["#FFF6BD", "#CEEDC7", "#86C8BC"],
    verse: "",
  },
  {
    id: "sad",
    title: "Sad",
    path: "/sad",
    color: ["#76A5FF", "#878EBA", "#AABBFF"],
    verse: "",
  },
  {
    id: "angry",
    title: "Angry",
    path: "/angry",
    color: ["#E4508F", "#FF8868", "#FFD35C"],
    verse: "3:159",
  },
  {
    id: "scared",
    title: "Scared",
    path: "/scared",
    color: ["#41444B", "#52575D", "#CABFAB"],
    verse: "",
  },
  {
    id: "lonely",
    title: "Lonely",
    path: "/lonely",
    color: ["#BBBBBB", "#A19EB0", "#FAF8FF"],
    verse: "",
  },
  {
    id: "weak",
    title: "Weak",
    path: "/weak",
    color: ["#93BFCF", "#85AAC7", "#C2F9FF"],
    verse: "",
  },
  {
    id: "worried",
    title: "Worried",
    path: "/worried",
    color: ["#B08BBB", "#8587C1", "#7B5986"],
    verse: "",
  },
  {
    id: "anxious",
    title: "Anxious",
    path: "/anxious",
    color: ["#B1B2FF", "#D2DAFF", "#AAC4FF"],
    verse: "",
  },
  {
    id: "forgiveness",
    title: "Need Forgiveness",
    path: "/forgiveness",
    color: ["#1572A1", "#4372AD", "#AE64A6"],
    verse: "",
  },
  {
    id: "need-courage",
    title: "Need Courage",
    path: "/need-courage",
    color: ["#F1935C", "#FF878C", "#FFBEC1"],
    verse: "",
  },
  {
    id: "need-direction",
    title: "Need Direction",
    path: "/need-direction",
    color: ["#555555", "#202020", "#505050"],
    verse: "",
  },
  {
    id: "peace",
    title: "Need Peace",
    path: "/need-peace",
    color: ["#FDFDBD", "#C4C487", "#C9E19F"],
    verse: "",
  },
  {
    id: "sinned",
    title: "Sinned",
    path: "/sinned",
    color: ["#535962", "#505680", "#60728C"],
    verse: "",
  },
  {
    id: "danger",
    title: "In Danger",
    path: "/danger",
    color: ["#EB6383", "#BD574E", "#D45079"],
    verse: "",
  },
  {
    id: "faith",
    title: "Lack of Faith",
    path: "/faith",
    color: ["#6E85B7", "#32A5D4", "#00C3D5"],
    verse: "",
  },
  {
    id: "sexually-discriminated",
    title: "Sexually Discriminated",
    path: "/sexually-discriminated",
    color: ["#BA90C6", "#B2A4FF", "#E8A0BF"],
    verse: "",
  },
  {
    id: "racially-discriminated",
    title: "Racially Discriminated",
    path: "/racially-discriminated",
    color: ["#F4B183", "#FFF8EA", "#815B5B"],
    verse: "",
  },
  {
    id: "depressed",
    title: "Depressed",
    path: "/depressed",
    color: ["#374259", "#A4ABBD", "#404756"],
    verse: "",
  },
  {
    id: "need-love",
    title: "Need Love and Tranquility",
    path: "/need-love",
    color: ["#FF8787", "#F8C4B4", "#BCE29E"],
    verse: "",
  },
  {
    id: "not-appreciated",
    title: "Not Appreciated",
    path: "/not-appreciated",
    color: ["#A97155", "#8FBDD3", "#BE8C63"],
    verse: "",
  },
  {
    id: "loser",
    title: "Like a Loser",
    path: "/loser",
    color: ["#D45D79", "#EA9085", "#F2D388"],
    verse: "",
  },
  {
    id: "underpriviledged",
    title: "Underpriviledged",
    path: "/underpriviledged",
    color: ["#85603F", "#9E7540", "#766161"],
    verse: "",
  },
  {
    id: "hardships",
    title: "Tired of Hardships",
    path: "/hardships",
    color: ["#838383", "#474554", "#707B83"],
    verse: "",
  },
];
